"""Initial migration.

Revision ID: 24ccfcd77ee8
Revises: 8173826524d9
Create Date: 2021-12-19 02:20:40.217717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24ccfcd77ee8'
down_revision = '8173826524d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blogs', sa.Column('blog_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogs', 'blog_url')
    # ### end Alembic commands ###
