"""Initial migration.

Revision ID: 394b620f7283
Revises: 
Create Date: 2021-12-16 18:57:52.295544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '394b620f7283'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('home', 'home_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('home', sa.Column('home_img', sa.VARCHAR(length=150), nullable=True))
    op.drop_table('user')
    # ### end Alembic commands ###
