"""test

Revision ID: 7cae2195cf91
Revises: edaeae09969a
Create Date: 2021-12-18 14:58:49.491721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7cae2195cf91'
down_revision = 'edaeae09969a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'project_detail')
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.VARCHAR(length=100), nullable=True))
    op.add_column('projects', sa.Column('project_detail', sa.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
