"""test

Revision ID: 8173826524d9
Revises: a404bb54d451
Create Date: 2021-12-18 19:01:36.985608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8173826524d9'
down_revision = 'a404bb54d451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('contact_title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contact', 'contact_title')
    # ### end Alembic commands ###
