"""Initial migration.

Revision ID: c74b1d1c9881
Revises: 64f14ea487d3
Create Date: 2021-12-17 21:49:35.470203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c74b1d1c9881'
down_revision = '64f14ea487d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skills_img', sa.String(length=150), nullable=True),
    sa.Column('skills_title', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skills')
    # ### end Alembic commands ###
