"""Initial migration.

Revision ID: edaeae09969a
Revises: c74b1d1c9881
Create Date: 2021-12-18 03:10:52.649504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edaeae09969a'
down_revision = 'c74b1d1c9881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_url', sa.Text(), nullable=True),
    sa.Column('project_img', sa.String(length=100), nullable=True),
    sa.Column('project_name', sa.String(length=100), nullable=True),
    sa.Column('project_detail', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    # ### end Alembic commands ###
